### PR TITLE
Us08

### PR DESCRIPTION
**Pull request by halilarslan1999**
Please commit

### CODE REVIEW

**Comment by halilarslan1999** [comment]
Review it

**Comment by sumermehmet2001** [comment]
confirmed

**Review by sumermehmet2001 — COMMENTED** [review]
confirmed

**Review by sumermehmet2001 — APPROVED** [review]

**Comment by halilarslan1999** [comment]
ok

**Review by sumermehmet2001 — APPROVED** [review]

**Review by halilarslan1999 — COMMENTED** [review]
ok

**Comment by halilarslan1999** [comment]
again reviewed

**Comment by halilarslan1999** [comment]
yapsana

**Comment by halilarslan1999** [comment]
Bir  daha

**Review by sumermehmet2001 — APPROVED** [review]

**Pull request closed without merging**
